package vista;

import getset.gsAutor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.conexion;
import modelo.modAutor;

/**
 *
 * @author EVA Tester
 */
public class frmAutor extends javax.swing.JFrame {

    private conexion mysql = new conexion();
    private Connection cn = mysql.conectar();
    String sSQL = "";

    public frmAutor() {
        initComponents();
        mostrar("");
        vaciarCampos();
        centrarFormulario();
    }
    private String accion = "guardar";

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            modAutor func = new modAutor();
            modelo = func.mostrar(buscar);
            tablaAutor.setModel(modelo);
            lbltotalregistros.setText("Total Registros " + func.totalregistros);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    void centrarFormulario() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsup = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        panelcentro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblIDAutor = new javax.swing.JLabel();
        lblNombreAutor = new javax.swing.JLabel();
        txtIDAutor = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        scrollPanel = new javax.swing.JScrollPane();
        tablaAutor = new javax.swing.JTable();
        lbltotalregistros = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFormularios = new javax.swing.JMenu();
        jMenuItemLibros = new javax.swing.JMenuItem();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemEditoriales = new javax.swing.JMenuItem();
        jMenuItemPrestamos = new javax.swing.JMenuItem();
        jSeparador = new javax.swing.JPopupMenu.Separator();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE INFORMACIÓN DE AUTORES");
        setResizable(false);
        setSize(new java.awt.Dimension(431, 299));

        panelsup.setBackground(new java.awt.Color(250, 147, 8));

        lblTituloForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setText("Registro de Información de Autores");

        panelcentro.setBackground(new java.awt.Color(45, 62, 82));

        btnRegistrar.setBackground(new java.awt.Color(52, 176, 240));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(52, 176, 240));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(253, 50, 36));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(52, 176, 240));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblIDAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIDAutor.setForeground(new java.awt.Color(255, 255, 255));
        lblIDAutor.setText("ID Autor");

        lblNombreAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombreAutor.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAutor.setText("Nombre");

        txtIDAutor.setBackground(new java.awt.Color(109, 125, 140));
        txtIDAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIDAutor.setForeground(new java.awt.Color(255, 255, 255));
        txtIDAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtIDAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDAutorActionPerformed(evt);
            }
        });

        txtAutor.setBackground(new java.awt.Color(109, 125, 140));
        txtAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(255, 255, 255));
        txtAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        scrollPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollPanelMouseClicked(evt);
            }
        });

        tablaAutor.setBackground(new java.awt.Color(109, 125, 140));
        tablaAutor.setForeground(new java.awt.Color(255, 255, 255));
        tablaAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Autor", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAutorMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(tablaAutor);

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("Total Registros");

        javax.swing.GroupLayout panelcentroLayout = new javax.swing.GroupLayout(panelcentro);
        panelcentro.setLayout(panelcentroLayout);
        panelcentroLayout.setHorizontalGroup(
            panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAutor)
                            .addComponent(lblIDAutor))
                        .addGap(18, 18, 18)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDAutor)
                            .addComponent(txtAutor))))
                .addGap(18, 18, 18)
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregistros)
                .addGap(138, 138, 138))
        );
        panelcentroLayout.setVerticalGroup(
            panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTituloForm)
                .addContainerGap(83, Short.MAX_VALUE))
            .addComponent(panelcentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuFormularios.setText("Formularios");

        jMenuItemLibros.setText("Libros");
        jMenuItemLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemLibros);

        jMenuItemGeneros.setText("Géneros");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemGeneros);

        jMenuItemEditoriales.setText("Editoriales");
        jMenuItemEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditorialesActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemEditoriales);

        jMenuItemPrestamos.setText("Prestamos");
        jMenuItemPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrestamosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemPrestamos);
        jMenuFormularios.add(jSeparador);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemUsuarios);

        jMenuBar.add(jMenuFormularios);

        jMenuLogin.setText("Login");

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemCerrarSesion);

        jMenuBar.add(jMenuLogin);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaciarCampos() {
        txtIDAutor.setText("");
        txtAutor.setText("");
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        gsAutor dts = new gsAutor();
        modAutor func = new modAutor();

        int idautor = Integer.parseInt(txtIDAutor.getText());
        dts.setIdAutor(idautor);
        dts.setNombreAutor(txtAutor.getText());

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Registo exitoso");
                vaciarCampos();
                mostrar("");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        /*if (!txtIDAutor.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Editar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modAutor func = new modAutor();
                gsAutor dts = new gsAutor();

                int idautor = Integer.parseInt(txtIDAutor.getText());
                dts.setIdAutor(idautor);
                func.editar(dts);
                mostrar("");
                accion = "guardar";
            }
        }*/

        try {
            String idautor = txtIDAutor.getText();
            String nombre = txtAutor.getText();

            sSQL = "update autor set idAutor='" + idautor + "', nombreAutor='" + nombre + "' where idAutor='" + idautor + "'";

            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.execute();

            JOptionPane.showMessageDialog(rootPane, "Registo editado");
            vaciarCampos();
            mostrar("");
            accion = "guardar";
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtIDAutor.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modAutor func = new modAutor();
                gsAutor dts = new gsAutor();

                dts.setIdAutor(Integer.parseInt(txtIDAutor.getText()));
                func.eliminar(dts);
                vaciarCampos();
                mostrar("");
                accion = "guardar";
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        vaciarCampos();
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIDAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDAutorActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void scrollPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollPanelMouseClicked

    }//GEN-LAST:event_scrollPanelMouseClicked

    private void tablaAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAutorMouseClicked
        accion = "editar";

        int fila = tablaAutor.rowAtPoint(evt.getPoint());
        txtIDAutor.setText(tablaAutor.getValueAt(fila, 0).toString());
        txtAutor.setText(tablaAutor.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablaAutorMouseClicked

    private void jMenuItemLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosActionPerformed
        this.setVisible(false);
        frmLibro nuevoform = new frmLibro();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemLibrosActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.setVisible(false);
        frmLogin nuevoform = new frmLogin();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        this.setVisible(false);
        frmGenero nuevoform = new frmGenero();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditorialesActionPerformed
        this.setVisible(false);
        frmEditorial nuevoform = new frmEditorial();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditorialesActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        this.setVisible(false);
        frmUsuario nuevoform = new frmUsuario();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrestamosActionPerformed
        this.setVisible(false);
        frmPrestamos nuevoform = new frmPrestamos();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFormularios;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemEditoriales;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemLibros;
    private javax.swing.JMenuItem jMenuItemPrestamos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JPopupMenu.Separator jSeparador;
    private javax.swing.JLabel lblIDAutor;
    private javax.swing.JLabel lblNombreAutor;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JPanel panelcentro;
    private javax.swing.JPanel panelsup;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tablaAutor;
    public javax.swing.JTextField txtAutor;
    public javax.swing.JTextField txtIDAutor;
    // End of variables declaration//GEN-END:variables
}
