package vista;

import getset.gsEditorial;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.conexion;
import modelo.modEditorial;

/**
 *
 * @author EVA Tester
 */
public class frmEditorial extends javax.swing.JFrame {

    private conexion mysql = new conexion();
    private Connection cn = mysql.conectar();
    private String sSQL = "";

    public frmEditorial() {
        initComponents();
        mostrar("");
        vaciarCampos();
        centrarFormulario();
    }
    private String accion = "guardar";

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            modEditorial func = new modEditorial();
            modelo = func.mostrar(buscar);
            tablaEditorial.setModel(modelo);
            lbltotalregistros.setText("Total Registros " + func.totalregistros);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    void centrarFormulario() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void vaciarCampos() {
        txtIDEditorial.setText("");
        txtNombreEditorial.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsup = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        panelcentro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblIDEditorial = new javax.swing.JLabel();
        lblNombreEditorial = new javax.swing.JLabel();
        txtIDEditorial = new javax.swing.JTextField();
        txtNombreEditorial = new javax.swing.JTextField();
        scrollPanel = new javax.swing.JScrollPane();
        tablaEditorial = new javax.swing.JTable();
        lbltotalregistros = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblIDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFormularios = new javax.swing.JMenu();
        jMenuItemLibros = new javax.swing.JMenuItem();
        jMenuItemAutores = new javax.swing.JMenuItem();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemPrestamos = new javax.swing.JMenuItem();
        jSeparador = new javax.swing.JPopupMenu.Separator();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE INFORMACIÓN DE EDITORIALES");
        setPreferredSize(new java.awt.Dimension(500, 406));
        setResizable(false);

        panelsup.setBackground(new java.awt.Color(250, 147, 8));

        lblTituloForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setText("Registro de Información de Editoriales");

        panelcentro.setBackground(new java.awt.Color(45, 62, 82));

        btnRegistrar.setBackground(new java.awt.Color(52, 176, 240));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(52, 176, 240));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(253, 50, 36));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(52, 176, 240));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblIDEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIDEditorial.setForeground(new java.awt.Color(255, 255, 255));
        lblIDEditorial.setText("ID Editorial");

        lblNombreEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombreEditorial.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEditorial.setText("Nombre Editorial");

        txtIDEditorial.setBackground(new java.awt.Color(109, 125, 140));
        txtIDEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIDEditorial.setForeground(new java.awt.Color(255, 255, 255));
        txtIDEditorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtIDEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEditorialActionPerformed(evt);
            }
        });

        txtNombreEditorial.setBackground(new java.awt.Color(109, 125, 140));
        txtNombreEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreEditorial.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreEditorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNombreEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEditorialActionPerformed(evt);
            }
        });

        tablaEditorial.setBackground(new java.awt.Color(109, 125, 140));
        tablaEditorial.setForeground(new java.awt.Color(255, 255, 255));
        tablaEditorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Editorial", "Nombre", "Dirección", "Nro. de Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEditorialMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(tablaEditorial);

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("Total Registros");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono");

        lblIDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblIDireccion.setText("Dirección");

        txtDireccion.setBackground(new java.awt.Color(109, 125, 140));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtTelefono.setBackground(new java.awt.Color(109, 125, 140));
        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcentroLayout = new javax.swing.GroupLayout(panelcentro);
        panelcentro.setLayout(panelcentroLayout);
        panelcentroLayout.setHorizontalGroup(
            panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregistros)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addComponent(lblIDEditorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDEditorial))
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addComponent(lblNombreEditorial)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreEditorial))
                    .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIDireccion))
                        .addGap(18, 18, 18)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion)
                            .addComponent(txtTelefono))))
                .addGap(18, 18, 18)
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelcentroLayout.setVerticalGroup(
            panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelcentroLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblTituloForm)
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(panelcentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuFormularios.setText("Formularios");

        jMenuItemLibros.setText("Libros");
        jMenuItemLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemLibros);

        jMenuItemAutores.setText("Autores");
        jMenuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoresActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemAutores);

        jMenuItemGeneros.setText("Generos");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemGeneros);

        jMenuItemPrestamos.setText("Prestamos");
        jMenuItemPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrestamosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemPrestamos);
        jMenuFormularios.add(jSeparador);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemUsuarios);

        jMenuBar.add(jMenuFormularios);

        jMenuLogin.setText("Login");

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemCerrarSesion);

        jMenuBar.add(jMenuLogin);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        gsEditorial dts = new gsEditorial();
        modEditorial func = new modEditorial();

        int ideditorial = Integer.parseInt(txtIDEditorial.getText());
        dts.setIdEditorial(ideditorial);
        dts.setNombreEditorial(txtNombreEditorial.getText());
        dts.setDireccEditorial(txtDireccion.getText());
        int telefeditorial = Integer.parseInt(txtTelefono.getText());
        dts.setTelefEditorial(telefeditorial);

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Registo exitoso");
                vaciarCampos();
                mostrar("");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        /*if (!txtIDEditorial.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Editar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modEditorial func = new modEditorial();
                gsEditorial dts = new gsEditorial();

                int ideditorial = Integer.parseInt(txtIDEditorial.getText());
                dts.setIdEditorial(ideditorial);
                func.editar(dts);
                mostrar("");
                accion = "guardar";
            }
        }*/

        try {
            String ideditorial = txtIDEditorial.getText();
            String nombre = txtNombreEditorial.getText();
            String direcc = txtDireccion.getText();
            String telef = txtTelefono.getText();

            sSQL = "update editorial set idEditorial='" + ideditorial + "', nombreEditorial='" + nombre + "',"
                    + "direccEditorial='" + direcc + "', telefEditorial='" + telef + "' where idEditorial='" + ideditorial + "'";

            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.execute();

            JOptionPane.showMessageDialog(rootPane, "Registo editado");
            vaciarCampos();
            mostrar("");
            accion = "guardar";
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtIDEditorial.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modEditorial func = new modEditorial();
                gsEditorial dts = new gsEditorial();

                dts.setIdEditorial(Integer.parseInt(txtIDEditorial.getText()));
                func.eliminar(dts);
                vaciarCampos();
                mostrar("");
                accion = "guardar";
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        vaciarCampos();
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIDEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEditorialActionPerformed

    private void txtNombreEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditorialActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void tablaEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEditorialMouseClicked
        accion = "editar";

        int fila = tablaEditorial.rowAtPoint(evt.getPoint());
        txtIDEditorial.setText(tablaEditorial.getValueAt(fila, 0).toString());
        txtNombreEditorial.setText(tablaEditorial.getValueAt(fila, 1).toString());
        txtDireccion.setText(tablaEditorial.getValueAt(fila, 2).toString());
        txtTelefono.setText(tablaEditorial.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tablaEditorialMouseClicked

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.setVisible(false);
        frmLogin nuevoform = new frmLogin();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosActionPerformed
        this.setVisible(false);
        frmLibro nuevoform = new frmLibro();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemLibrosActionPerformed

    private void jMenuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoresActionPerformed
        this.setVisible(false);
        frmAutor nuevoform = new frmAutor();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemAutoresActionPerformed

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        this.setVisible(false);
        frmGenero nuevoform = new frmGenero();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        this.setVisible(false);
        frmUsuario nuevoform = new frmUsuario();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrestamosActionPerformed
        this.setVisible(false);
        frmPrestamos nuevoform = new frmPrestamos();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFormularios;
    private javax.swing.JMenuItem jMenuItemAutores;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemLibros;
    private javax.swing.JMenuItem jMenuItemPrestamos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JPopupMenu.Separator jSeparador;
    private javax.swing.JLabel lblIDEditorial;
    private javax.swing.JLabel lblIDireccion;
    private javax.swing.JLabel lblNombreEditorial;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JPanel panelcentro;
    private javax.swing.JPanel panelsup;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tablaEditorial;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtIDEditorial;
    public javax.swing.JTextField txtNombreEditorial;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
