package vista;

import getset.gsLibro;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.conexion;
import modelo.modLibro;

/**
 *
 * @author EVA Tester
 */
public class frmLibro extends javax.swing.JFrame {

    private conexion mysql = new conexion();
    private Connection cn = mysql.conectar();
    private String sSQL = "";

    public frmLibro() {
        initComponents();
        mostrar("");
        llenarcmbAutor();
        llenarcmbGenero();
        llenarcmbEditorial();
        vaciarCampos();
        centrarFormulario();
    }
    private String accion = "guardar";

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            modLibro func = new modLibro();
            modelo = func.mostrar(buscar);
            tablaLibro.setModel(modelo);
            lbltotalregistros.setText("Total Registros " + func.totalregistros);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    void centrarFormulario() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelsup = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        panelizq = new javax.swing.JPanel();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        lblAnho = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtFechaPublic = new javax.swing.JTextField();
        cmbEditorial = new javax.swing.JComboBox<>();
        cmbAutor = new javax.swing.JComboBox<>();
        cmbGenero = new javax.swing.JComboBox<>();
        panelder = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblAmericanaLogo = new javax.swing.JLabel();
        panelinf = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tablaLibro = new javax.swing.JTable();
        lbltotalregistros = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFormularios = new javax.swing.JMenu();
        jMenuItemAutores = new javax.swing.JMenuItem();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemEditoriales = new javax.swing.JMenuItem();
        jMenuItemPrestamos = new javax.swing.JMenuItem();
        jSeparador = new javax.swing.JPopupMenu.Separator();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE INFORMACIÓN DE LIBROS");
        setBackground(new java.awt.Color(45, 62, 82));
        setForeground(java.awt.Color.white);
        setResizable(false);

        panelsup.setBackground(new java.awt.Color(250, 147, 8));

        lblTituloForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setText("Registro de Información de Libros");

        panelizq.setBackground(new java.awt.Color(45, 62, 82));

        lblISBN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(255, 255, 255));
        lblISBN.setText("ISBN");

        txtISBN.setBackground(new java.awt.Color(109, 125, 140));
        txtISBN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtISBN.setForeground(new java.awt.Color(255, 255, 255));
        txtISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Título");

        txtTitulo.setBackground(new java.awt.Color(109, 125, 140));
        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor.setText("Autor");

        lblAnho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAnho.setForeground(new java.awt.Color(255, 255, 255));
        lblAnho.setText("Fecha de Public.");

        lblEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditorial.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorial.setText("Editoral");

        lblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Género");

        lblStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("Stock");

        txtStock.setBackground(new java.awt.Color(109, 125, 140));
        txtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtFechaPublic.setBackground(new java.awt.Color(109, 125, 140));
        txtFechaPublic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaPublic.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaPublic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFechaPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPublicActionPerformed(evt);
            }
        });

        cmbEditorial.setBackground(new java.awt.Color(109, 125, 140));
        cmbEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditorialActionPerformed(evt);
            }
        });

        cmbAutor.setBackground(new java.awt.Color(109, 125, 140));
        cmbAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbAutor.setBorder(null);

        cmbGenero.setBackground(new java.awt.Color(109, 125, 140));
        cmbGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        panelder.setBackground(new java.awt.Color(45, 62, 82));

        btnRegistrar.setBackground(new java.awt.Color(52, 176, 240));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(52, 176, 240));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(52, 176, 240));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(253, 50, 36));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblAmericanaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/americana2.png"))); // NOI18N

        javax.swing.GroupLayout panelderLayout = new javax.swing.GroupLayout(panelder);
        panelder.setLayout(panelderLayout);
        panelderLayout.setHorizontalGroup(
            panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelderLayout.createSequentialGroup()
                .addGroup(panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelderLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblAmericanaLogo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelderLayout.setVerticalGroup(
            panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmericanaLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );

        panelinf.setBackground(new java.awt.Color(45, 62, 82));

        scrollPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaLibro.setBackground(new java.awt.Color(109, 125, 140));
        tablaLibro.setForeground(new java.awt.Color(255, 255, 255));
        tablaLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Título", "Autor", "Género", "Editorial", "Fecha Public.", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibroMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(tablaLibro);

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("Total Registros");

        javax.swing.GroupLayout panelinfLayout = new javax.swing.GroupLayout(panelinf);
        panelinf.setLayout(panelinfLayout);
        panelinfLayout.setHorizontalGroup(
            panelinfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregistros)
                .addGap(44, 44, 44))
        );
        panelinfLayout.setVerticalGroup(
            panelinfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfLayout.createSequentialGroup()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelizqLayout = new javax.swing.GroupLayout(panelizq);
        panelizq.setLayout(panelizqLayout);
        panelizqLayout.setHorizontalGroup(
            panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelizqLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addComponent(lblISBN)
                        .addGap(16, 16, 16)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(10, 10, 10)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addComponent(lblAutor)
                        .addGap(14, 14, 14)
                        .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addComponent(lblAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtFechaPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addGap(7, 7, 7)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblEditorial)
                        .addGap(4, 4, 4)
                        .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelinf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelizqLayout.setVerticalGroup(
            panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelizqLayout.createSequentialGroup()
                .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelizqLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelizqLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblStock))
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelizqLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblAutor))
                            .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelizqLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblAnho))
                            .addComponent(txtFechaPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelizqLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGenero)
                                    .addComponent(lblEditorial)))))
                    .addComponent(panelder, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(panelinf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(lblTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(161, 161, 161))
            .addComponent(panelizq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelizq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuFormularios.setText("Formularios");

        jMenuItemAutores.setText("Autores");
        jMenuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoresActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemAutores);

        jMenuItemGeneros.setText("Géneros");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemGeneros);

        jMenuItemEditoriales.setText("Editoriales");
        jMenuItemEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditorialesActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemEditoriales);

        jMenuItemPrestamos.setText("Prestamos");
        jMenuItemPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrestamosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemPrestamos);
        jMenuFormularios.add(jSeparador);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemUsuarios);

        jMenuBar.add(jMenuFormularios);

        jMenuLogin.setText("Login");

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemCerrarSesion);

        jMenuBar.add(jMenuLogin);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaciarCampos() {
        txtISBN.setText("");
        txtTitulo.setText("");
        txtFechaPublic.setText("");
        txtStock.setText("");
        cmbAutor.setSelectedIndex(-1);
        cmbGenero.setSelectedIndex(-1);
        cmbEditorial.setSelectedIndex(-1);
    }

    private void tablaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibroMouseClicked
        accion = "editar";

        int fila = tablaLibro.rowAtPoint(evt.getPoint());
        txtISBN.setText(tablaLibro.getValueAt(fila, 0).toString());
        txtTitulo.setText(tablaLibro.getValueAt(fila, 1).toString());
        cmbAutor.setSelectedItem(tablaLibro.getValueAt(fila, 2).toString());
        cmbGenero.setSelectedItem(tablaLibro.getValueAt(fila, 3).toString());
        cmbEditorial.setSelectedItem(tablaLibro.getValueAt(fila, 4).toString());
        txtFechaPublic.setText(tablaLibro.getValueAt(fila, 5).toString());
        txtStock.setText(tablaLibro.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_tablaLibroMouseClicked

    private void txtFechaPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPublicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPublicActionPerformed

    private void llenarcmbAutor() {
        try {
            sSQL = "select * from autor";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                String nombre = rs.getString("nombreAutor");
                cmbAutor.addItem(nombre);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void llenarcmbGenero() {
        try {
            sSQL = "select * from genero";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                String nombre = rs.getString("descGenero");
                cmbGenero.addItem(nombre);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void llenarcmbEditorial() {
        try {
            sSQL = "select * from editorial";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                String nombre = rs.getString("nombreEditorial");
                cmbEditorial.addItem(nombre);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void cmbEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEditorialActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtISBN.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modLibro func = new modLibro();
                gsLibro dts = new gsLibro();

                dts.setIsbn(txtISBN.getText());
                func.eliminar(dts);
                vaciarCampos();
                mostrar("");
                accion = "guardar";
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        vaciarCampos();
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        /*if (!txtISBN.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Editar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modLibro func = new modLibro();
                gsLibro dts = new gsLibro();

                dts.setIsbn(txtISBN.getText());
                func.editar(dts);
                mostrar("");
                accion = "guardar";
            }
        }*/

        try {
            String idlibro = txtISBN.getText();
            String stock = txtStock.getText();
            String titulo = txtTitulo.getText();
            String fecha = txtFechaPublic.getText();

            String autor = (String) cmbAutor.getSelectedItem();
            String editorial = (String) cmbEditorial.getSelectedItem();
            String genero = (String) cmbGenero.getSelectedItem();

            sSQL = "update libros set idLibro='" + idlibro + "', tituloLibro='" + titulo + "', autor='" + autor + "',"
                    + "genero='" + genero + "', editorial='" + editorial + "', anhoPublic='" + fecha + "',"
                    + "stock='" + stock + "' where idLibro='" + idlibro + "'";

            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.execute();

            JOptionPane.showMessageDialog(rootPane, "Registo editado");
            vaciarCampos();
            mostrar("");
            accion = "guardar";
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        /*if ((txtISBN.getText().length() == 0) || (txtTitulo.getText().length() == 0) || (cmbAutor.getText().length() == 0) || (cmbGenero.getText().length() == 0) || (cmbEditorial.getText().length() == 0) || (txtStock.getText().length() == 0)) {
            JOptionPane.showMessageDialog(rootPane, "Asegúrate de llenar todos los campos.");
        }*/

        gsLibro dts = new gsLibro();
        modLibro func = new modLibro();

        dts.setIsbn(txtISBN.getText());
        dts.setTitulo(txtTitulo.getText());

        int seleccionAutor = cmbAutor.getSelectedIndex();
        dts.setAutor((String) cmbAutor.getItemAt(seleccionAutor));
        int seleccionGenero = cmbGenero.getSelectedIndex();
        dts.setGenero((String) cmbGenero.getItemAt(seleccionGenero));
        int seleccionEditorial = cmbEditorial.getSelectedIndex();
        dts.setEditorial((String) cmbEditorial.getItemAt(seleccionEditorial));
        dts.setFechaPublic(txtFechaPublic.getText());
        dts.setStock(txtStock.getText());

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Registo exitoso");
                vaciarCampos();
                mostrar("");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jMenuItemEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditorialesActionPerformed
        this.setVisible(false);
        frmEditorial nuevoform = new frmEditorial();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditorialesActionPerformed

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        this.setVisible(false);
        frmGenero nuevoform = new frmGenero();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoresActionPerformed
        this.setVisible(false);
        frmAutor nuevoform = new frmAutor();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemAutoresActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        this.setVisible(false);
        frmUsuario nuevoform = new frmUsuario();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.setVisible(false);
        frmLogin nuevoform = new frmLogin();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrestamosActionPerformed
        this.setVisible(false);
        frmPrestamos nuevoform = new frmPrestamos();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbAutor;
    private javax.swing.JComboBox<String> cmbEditorial;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFormularios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAutores;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemEditoriales;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemPrestamos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JPopupMenu.Separator jSeparador;
    private javax.swing.JLabel lblAmericanaLogo;
    private javax.swing.JLabel lblAnho;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JPanel panelder;
    private javax.swing.JPanel panelinf;
    private javax.swing.JPanel panelizq;
    private javax.swing.JPanel panelsup;
    public javax.swing.JScrollPane scrollPanel;
    public javax.swing.JTable tablaLibro;
    private javax.swing.JTextField txtFechaPublic;
    public javax.swing.JTextField txtISBN;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
