package vista;

import getset.gsPrestamo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.conexion;
import modelo.modPrestamo;

/**
 *
 * @author EVA Tester
 */
public class frmPrestamos extends javax.swing.JFrame {

    private conexion mysql = new conexion();
    private Connection cn = mysql.conectar();
    private String sSQL = "";

    public frmPrestamos() {
        initComponents();
        mostrar("");
        llenarcmbLibro();
        vaciarCampos();
        centrarFormulario();
    }
    private String accion = "guardar";

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            modPrestamo func = new modPrestamo();
            modelo = func.mostrar(buscar);
            tablaPrestamos.setModel(modelo);
            lbltotalregistros.setText("Total Registros " + func.totalregistros);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    void centrarFormulario() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtCICliente = new javax.swing.JTextField();
        lblCICliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbPrestLibro1 = new javax.swing.JComboBox<>();
        cmbPrestLibro2 = new javax.swing.JComboBox<>();
        cmbPrestLibro3 = new javax.swing.JComboBox<>();
        lblPrestLibro1 = new javax.swing.JLabel();
        lblPrestLibro2 = new javax.swing.JLabel();
        lblPrestLibro3 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        lblFechaPrest = new javax.swing.JLabel();
        lbltotalregistros = new javax.swing.JLabel();
        txtCantLibro1 = new javax.swing.JTextField();
        txtCantLibro2 = new javax.swing.JTextField();
        txtCantLibro3 = new javax.swing.JTextField();
        lblNombreCliente1 = new javax.swing.JLabel();
        lblCantLibro1 = new javax.swing.JLabel();
        lblCantLibro3 = new javax.swing.JLabel();
        txtFechaPrest = new javax.swing.JTextField();
        txtFechaDevol = new javax.swing.JTextField();
        lblFechaDevol = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        lblicono = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFormularios = new javax.swing.JMenu();
        jMenuItemLibros = new javax.swing.JMenuItem();
        jMenuItemAutores = new javax.swing.JMenuItem();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemEditoriales = new javax.swing.JMenuItem();
        jSeparador = new javax.swing.JPopupMenu.Separator();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIONAR PRÉSTAMOS Y DEVOLUCIONES");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 147, 8));

        jPanel2.setBackground(new java.awt.Color(45, 62, 82));

        txtNombreCliente.setBackground(new java.awt.Color(109, 125, 140));
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCliente.setText("Nombre del Cliente");

        txtCICliente.setBackground(new java.awt.Color(109, 125, 140));
        txtCICliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCICliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCICliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblCICliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCICliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCICliente.setText("Cédula de Identidad");

        cmbPrestLibro1.setBackground(new java.awt.Color(109, 125, 140));
        cmbPrestLibro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbPrestLibro1.setBorder(null);
        cmbPrestLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrestLibro1ActionPerformed(evt);
            }
        });

        cmbPrestLibro2.setBackground(new java.awt.Color(109, 125, 140));
        cmbPrestLibro2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbPrestLibro2.setBorder(null);
        cmbPrestLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrestLibro2ActionPerformed(evt);
            }
        });

        cmbPrestLibro3.setBackground(new java.awt.Color(109, 125, 140));
        cmbPrestLibro3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbPrestLibro3.setBorder(null);
        cmbPrestLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrestLibro3ActionPerformed(evt);
            }
        });

        lblPrestLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrestLibro1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestLibro1.setText("Prestamo de libro 1:");

        lblPrestLibro2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrestLibro2.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestLibro2.setText("Prestamo de libro 2:");

        lblPrestLibro3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrestLibro3.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestLibro3.setText("Prestamo de libro 3:");

        tablaPrestamos.setBackground(new java.awt.Color(45, 62, 82));
        tablaPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Libro Prest. 1", "Cantidad", "Libro Prest. 2", "Cantidad", "Libro Prest. 3", "Cantidad", "Fecha Prest.", "Fecha Devol."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrestamosMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tablaPrestamos);

        lblFechaPrest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechaPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPrest.setText("Fecha de Préstamo");

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("Total Registros");

        txtCantLibro1.setBackground(new java.awt.Color(109, 125, 140));
        txtCantLibro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantLibro1.setForeground(new java.awt.Color(255, 255, 255));
        txtCantLibro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtCantLibro2.setBackground(new java.awt.Color(109, 125, 140));
        txtCantLibro2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantLibro2.setForeground(new java.awt.Color(255, 255, 255));
        txtCantLibro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtCantLibro3.setBackground(new java.awt.Color(109, 125, 140));
        txtCantLibro3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantLibro3.setForeground(new java.awt.Color(255, 255, 255));
        txtCantLibro3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblNombreCliente1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombreCliente1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCliente1.setText("Cantidad");

        lblCantLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantLibro1.setForeground(new java.awt.Color(255, 255, 255));
        lblCantLibro1.setText("Cantidad");

        lblCantLibro3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantLibro3.setForeground(new java.awt.Color(255, 255, 255));
        lblCantLibro3.setText("Cantidad");

        txtFechaPrest.setBackground(new java.awt.Color(109, 125, 140));
        txtFechaPrest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaPrest.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaPrest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtFechaDevol.setBackground(new java.awt.Color(109, 125, 140));
        txtFechaDevol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaDevol.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaDevol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblFechaDevol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechaDevol.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaDevol.setText("Fecha de Devolución");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbltotalregistros)
                .addGap(56, 56, 56))
            .addComponent(jScrollPane)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblCICliente))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtCICliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrestLibro1)
                            .addComponent(lblPrestLibro2)
                            .addComponent(lblPrestLibro3)
                            .addComponent(lblFechaPrest))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPrestLibro3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPrestLibro2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPrestLibro1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblCantLibro3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCantLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblCantLibro1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCantLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblNombreCliente1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCantLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFechaPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(lblFechaDevol)
                                .addGap(53, 53, 53)
                                .addComponent(txtFechaDevol, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCICliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPrestLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrestLibro1)
                    .addComponent(txtCantLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPrestLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrestLibro2)
                    .addComponent(txtCantLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantLibro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPrestLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrestLibro3)
                    .addComponent(txtCantLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantLibro3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFechaPrest)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaDevol)
                                    .addGap(7, 7, 7))
                                .addComponent(txtFechaDevol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFechaPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnNuevo.setBackground(new java.awt.Color(52, 176, 240));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnPrestar.setBackground(new java.awt.Color(52, 176, 240));
        btnPrestar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrestar.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestar.setText("Prestar");
        btnPrestar.setBorder(null);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnDevolver.setBackground(new java.awt.Color(52, 176, 240));
        btnDevolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDevolver.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolver.setText("Devolver");
        btnDevolver.setBorder(null);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cashbook-filled-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblicono)))
                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrestar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblicono)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuFormularios.setText("Formularios");

        jMenuItemLibros.setText("Libros");
        jMenuItemLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemLibros);

        jMenuItemAutores.setText("Autores");
        jMenuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoresActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemAutores);

        jMenuItemGeneros.setText("Géneros");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemGeneros);

        jMenuItemEditoriales.setText("Editoriales");
        jMenuItemEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditorialesActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemEditoriales);
        jMenuFormularios.add(jSeparador);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuFormularios.add(jMenuItemUsuarios);

        jMenuBar.add(jMenuFormularios);

        jMenuLogin.setText("Login");

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemCerrarSesion);

        jMenuBar.add(jMenuLogin);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaciarCampos() {
        txtCICliente.setText("");
        txtNombreCliente.setText("");
        txtCantLibro1.setText("");
        txtCantLibro2.setText("");
        txtCantLibro3.setText("");
        txtFechaPrest.setText("");
        txtFechaDevol.setText("");
        cmbPrestLibro1.setSelectedIndex(-1);
        cmbPrestLibro2.setSelectedIndex(-1);
        cmbPrestLibro3.setSelectedIndex(-1);
    }

    private void llenarcmbLibro() {
        try {
            sSQL = "select * from libros";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                String libro = rs.getString("tituloLibro");
                cmbPrestLibro1.addItem(libro);
                cmbPrestLibro2.addItem(libro);
                cmbPrestLibro3.addItem(libro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void jMenuItemLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosActionPerformed
        this.setVisible(false);
        frmLibro nuevoform = new frmLibro();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemLibrosActionPerformed

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        this.setVisible(false);
        frmGenero nuevoform = new frmGenero();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditorialesActionPerformed
        this.setVisible(false);
        frmEditorial nuevoform = new frmEditorial();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditorialesActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        this.setVisible(false);
        frmUsuario nuevoform = new frmUsuario();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.setVisible(false);
        frmLogin nuevoform = new frmLogin();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoresActionPerformed
        this.setVisible(false);
        frmAutor nuevoform = new frmAutor();
        nuevoform.setVisible(true);
    }//GEN-LAST:event_jMenuItemAutoresActionPerformed

    private void cmbPrestLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrestLibro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrestLibro1ActionPerformed

    private void cmbPrestLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrestLibro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrestLibro2ActionPerformed

    private void cmbPrestLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrestLibro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrestLibro3ActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        if (!txtNombreCliente.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {
                modPrestamo func = new modPrestamo();
                gsPrestamo dts = new gsPrestamo();

                dts.setNombreCliente(txtNombreCliente.getText());
                func.eliminar(dts);
                vaciarCampos();
                mostrar("");
                accion = "guardar";
            }
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        gsPrestamo dts = new gsPrestamo();
        modPrestamo func = new modPrestamo();

        int cicliente = Integer.parseInt(txtCICliente.getText());
        dts.setIdCliente(cicliente);

        dts.setCant1(Integer.parseInt(txtCantLibro1.getText()));
        dts.setCant2(Integer.parseInt(txtCantLibro2.getText()));
        dts.setCant3(Integer.parseInt(txtCantLibro3.getText()));

        dts.setNombreCliente(txtNombreCliente.getText());
        dts.setFechaPrest(txtFechaPrest.getText());
        dts.setFechaDevol(txtFechaDevol.getText());

        int seleccionLibro1 = cmbPrestLibro1.getSelectedIndex();
        dts.setLibro1((String) cmbPrestLibro1.getItemAt(seleccionLibro1));
        int seleccionLibro2 = cmbPrestLibro2.getSelectedIndex();
        dts.setLibro2((String) cmbPrestLibro2.getItemAt(seleccionLibro2));
        int seleccionLibro3 = cmbPrestLibro3.getSelectedIndex();
        dts.setLibro3((String) cmbPrestLibro3.getItemAt(seleccionLibro3));

        if (accion.equals("guardar")) {
            if ((func.insertarCli(dts)) && (func.insertarPrest(dts))) {
                JOptionPane.showMessageDialog(rootPane, "Registo exitoso");
                vaciarCampos();
                mostrar("");
            }
        }

    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        vaciarCampos();
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrestamosMouseClicked
        accion = "editar";
        
        int fila = tablaPrestamos.rowAtPoint(evt.getPoint());
        txtNombreCliente.setText(tablaPrestamos.getValueAt(fila, 0).toString());
        cmbPrestLibro1.setSelectedItem(tablaPrestamos.getValueAt(fila, 1).toString());
        txtCantLibro1.setText(tablaPrestamos.getValueAt(fila, 2).toString());
        cmbPrestLibro2.setSelectedItem(tablaPrestamos.getValueAt(fila, 3).toString());
        txtCantLibro2.setText(tablaPrestamos.getValueAt(fila, 4).toString());
        cmbPrestLibro3.setSelectedItem(tablaPrestamos.getValueAt(fila, 5).toString());
        txtCantLibro3.setText(tablaPrestamos.getValueAt(fila, 6).toString());
        txtFechaPrest.setText(tablaPrestamos.getValueAt(fila, 7).toString());
        txtFechaDevol.setText(tablaPrestamos.getValueAt(fila, 8).toString());
    }//GEN-LAST:event_tablaPrestamosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JComboBox<String> cmbPrestLibro1;
    private javax.swing.JComboBox<String> cmbPrestLibro2;
    private javax.swing.JComboBox<String> cmbPrestLibro3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFormularios;
    private javax.swing.JMenuItem jMenuItemAutores;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemEditoriales;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemLibros;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPopupMenu.Separator jSeparador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCICliente;
    private javax.swing.JLabel lblCantLibro1;
    private javax.swing.JLabel lblCantLibro3;
    private javax.swing.JLabel lblFechaDevol;
    private javax.swing.JLabel lblFechaPrest;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreCliente1;
    private javax.swing.JLabel lblPrestLibro1;
    private javax.swing.JLabel lblPrestLibro2;
    private javax.swing.JLabel lblPrestLibro3;
    private javax.swing.JLabel lblicono;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JTable tablaPrestamos;
    public javax.swing.JTextField txtCICliente;
    public javax.swing.JTextField txtCantLibro1;
    public javax.swing.JTextField txtCantLibro2;
    public javax.swing.JTextField txtCantLibro3;
    public javax.swing.JTextField txtFechaDevol;
    public javax.swing.JTextField txtFechaPrest;
    public javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
